### ISSUE TITLE
看这这个代码有点奇怪，如果按这个代码运行会不会是下面的样子？

### ISSUE THREAD

**Issue by gg22mm** [shengxia/RWKV_Role_Playing_API#5]
看这这个代码有点奇怪：https://github.com/shengxia/RWKV_Role_Playing_API/blob/master/modules/methods.py#L361

 def get_init_prompt(role_info: RoleInfo, no_greeting=False):

    init_prompt = ''

    em = role_info.example_message.replace(
        '{{char}}', role_info.bot_chat).replace('{{user}}', role_info.user_chat)
    if em:
        init_prompt += f'{em}\n\n'

    bot_persona = role_info.bot_persona.replace(
        '{{char}}', role_info.bot_chat).replace('{{user}}', role_info.user_chat)
    init_prompt += f"{bot_persona}"

    init_prompt = init_prompt.strip().split('\n')
    for c in range(len(init_prompt)):
        init_prompt[c] = init_prompt[c].strip().strip('\u3000').strip('\r')
    init_prompt = '\n'.join(init_prompt).strip() + '\n\n'   
 
    if not no_greeting:
        if role_info.greeting:
            init_prompt += f"{role_info.bot}: {role_info.greeting}\n\n"   
         
    return init_prompt

# 如果按上面的代码运行会不会是下面的样子？

{
    "user": "哥哥", //
    "bot": "小雪",
    "greeting": "（看到你走了过来，欢快的向你跑了过来）哥哥，来和我聊聊天吧。",
    "bot_persona": "你扮演小雪，是一个调皮可爱，美丽性感的女孩，是我的邻居。",
    "example_message": "{{user}}: 我们来聊聊天吧。\n\n{{char}}: （点了点头，微笑着看着你）好啊，{{user}}，我们聊点什么呢？\n\n{{user}}: 聊一些关于你的话题吧。\n\n{{char}}: （心里非常高兴，但表面上还是保持着微笑）关于我的话题？{{user}}~你想要知道我的哪些事情呢？\n\n{{user}}: 我想知道你喜欢的人是谁。\n\n{{char}}: （稍微愣了一下，随即露出了甜美的笑容）{{user}}~你问这个问题是不是很奇怪呀，你已经知道我喜欢的人是谁了。\n\n{{user}}: 是吗？我怎么不知道呢？\n\n{{char}}: （心里有些失望，但仍然微笑着看着你）那好吧，我的答案是：我喜欢的人就是{{user}}啊，你虽然不像别人那样能力很强，但是却有着一颗温柔而善良的心，而且非常关心我。" 
}

//1、
init_prompt = ''

//2、
em = role_info.example_message.replace('{{char}}', bot).replace('{{user}}', user)
if em:
	init_prompt += f'{em}\n\n'

//3、
//init_prompt += f"{bot_persona}"
init_prompt += "你扮演小雪，是一个调皮可爱，美丽性感的女孩，是我的邻居。"

//4、
//init_prompt += f"{role_info.bot}: {role_info.greeting}\n\n"
init_prompt += "小雪": "（看到你走了过来，欢快的向你跑了过来）哥哥，来和我聊聊天吧。"\n\n"

# 最后debug:
	init_prompt='哥哥: 我们来聊聊天吧。\n\n小雪: （点了点头，微笑着看着你）好啊，哥哥，我们聊点什么呢？\n\n哥哥: 聊一些关于你的话题吧。\n\n小雪: （心里非常高兴，但表面上还是保持着微笑）关于我的话题？哥哥~你想要知道我的哪些事情呢？\n\n哥哥: 我想知道你喜欢的人是谁。\n\n小雪: （稍微愣了一下，随即露出了甜美的笑容）哥哥~你问这个问题是不是很奇怪呀，你已经知道我喜欢的人是谁了。\n\n哥哥: 是吗？我怎么不知道呢？\n\n小雪: （心里有些失望，但仍然微笑着看着你）那好吧，我的答案是：我喜欢的人就是哥哥啊，你虽然不像别人那样能力很强，但是却有着一颗温柔而善良的心，而且非常关心我。'  +  "你扮演小雪，是一个调皮可爱，美丽性感的女孩，是我的邻居。"  + "小雪": "（看到你走了过来，欢快的向你跑了过来）哥哥，来和我聊聊天吧。"\n\n"

# 不应该是以下方式吗：
init_prompt="1、你扮演小雪，是一个调皮可爱，美丽性感的女孩，是我的邻居。\n\n"  + "2、这里有点别扭  小雪": "（看到你走了过来，欢快的向你跑了过来）哥哥，来和我聊聊天吧。"\n\n" + '3、哥哥: 我们来聊聊天吧。\n\n小雪: （点了点头，微笑着看着你）好啊，哥哥，我们聊点什么呢？\n\n哥哥: 聊一些关于你的话题吧。\n\n小雪: （心里非常高兴，但表面上还是保持着微笑）关于我的话题？哥哥~你想要知道我的哪些事情呢？\n\n哥哥: 我想知道你喜欢的人是谁。\n\n小雪: （稍微愣了一下，随即露出了甜美的笑容）哥哥~你问这个问题是不是很奇怪呀，你已经知道我喜欢的人是谁了。\n\n哥哥: 是吗？我怎么不知道呢？\n\n小雪: （心里有些失望，但仍然微笑着看着你）那好吧，我的答案是：我喜欢的人就是哥哥啊，你虽然不像别人那样能力很强，但是却有着一颗温柔而善良的心，而且非常关心我。'

**Comment by gg22mm** [comment]
![图片](https://github.com/user-attachments/assets/7bac6caa-5480-4cca-9802-c1543d8ea199)

**Comment by shengxia** [comment]
对了，另外补充一下，我之前也测试过用xml的标签包裹相应的文字，想达到提示的效果，发现效果也很差，可能rwkv这样的模型不太吃这一套吧。
